LilsCareApp/Controllers/TermsConditionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LilsCareApp.Controllers
{
    public class TermsConditionsController : BaseController
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

LilsCareApp/Views/Shared/_ContactUsPartial.cshtml
@inject IViewLocalizer Localizer
@model ContactUsDTO
@{
}

<h2 class="h1">@Localizer["ASK US"]</h2>
<p class="fs-6 mb-0">
    @Localizer["about the products, personal suggestions or share an opinion. Your experience will always be most important to us."]
</p>
<div class="d-flex justify-content-center">
    <div style="width: 60%">
        <div>
            <input asp-for="FirstName" type="name"
                   class="form-control"
                   placeholder="@Localizer["First Name"]*"
                   name="FirstName" />
        </div>
        <span asp-validation-for="@Model.FirstName" class="text-danger" style="font-size: 12px"></span>
        <div class="px-0 my-3">
            <input asp-for="LastName" type="name"
                   class="form-control"
                   placeholder="@Localizer["Last Name"]"
                   name="LastName" />
        </div>
        <div>
            <input asp-for="EmailForResponse" 
                   class="form-control"
                   placeholder="@Localizer["Email"]*"
                   name="EmailForResponse" />
        </div>
        <span asp-validation-for="@Model.EmailForResponse" class="text-danger" style="; font-size: 12px"></span>
        <button type="submit"
                class="btn btn-primary mt-3"
                style="width: 100%">
                @Localizer["Send"]
        </button>
        <div class="form-check" style="font-size: 14px">
            <label class="form-check-label">
                <input asp-for="PrivacyPolicy" type="checkbox"
                       class="form-check-input"
                       name="PrivacyPolicy"
                       data-val="true"
                       data-val-mustbetrue="@Localizer["Confirm agreement with the privacy policy."]" />
                @Localizer["I agree"] с&nbsp;
                <a asp-controller="TermsConditions" style="color: rgb(var(--app-btn-bg))"
                   target="_blank">
                    @Localizer["the conditions"]
                </a>
            </label>
        </div>
        <span asp-validation-for="@Model.PrivacyPolicy" class="text-danger" style="font: var(--font_9); font-size: 12px"></span>
    </div>
    <div style="width: 40%; padding-left: 15px">
        <textarea asp-for="Message" class="form-control"
                  rows="9"
                  name="Message"
                  placeholder="@Localizer["Write a message..."]"></textarea>
        <span asp-validation-for="@Model.Message" class="text-danger" style="font-size: 12px"></span>
        <label for="comment"
               style="font-size: 14px">
                @Localizer["We send an email 1 to 2 times a month."]
        </label>
    </div>
</div>

LilsCareApp/Views/Shared/_DeliveryToAddressPartial.cshtml
@inject IViewLocalizer Localizer
@model AddressOrderDTO

<!-- New Delivery Address Start -->
<form asp-action="AddAddressDelivery" method="post">
    <input asp-for="@Model.Id" value="@Model.Id" hidden />
    <input asp-for="@Model.DeliveryMethodId" value="@Model.DeliveryMethodId" hidden />
    <div class="row my-2">
        <div class="col-6">
            <label asp-for="@Model.FirstName" class="form-label small">@Localizer["First Name"]*</label>
            <input asp-for="@Model.FirstName"
                   type="text"
                   class="form-control" />
            <span asp-validation-for="@Model.FirstName" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="@Model.LastName" class="form-label small">@Localizer["Last Name"]*</label>
            <input asp-for="@Model.LastName"
                   type="text"
                   class="form-control" />
            <span asp-validation-for="@Model.LastName" class="text-danger"></span>
        </div>
    </div>
    <div class="row my-2">
        <div class="col-4">
            <label asp-for="@Model.Country" class="form-label small">@Localizer["Country"]*</label>
            <select asp-for="@Model.Country" class="form-select">
                <option>България</option>
            </select>
            <span asp-validation-for="@Model.Country" class="text-danger"></span>
        </div>
        <div class="col-3">
            <label asp-for="@Model.PostCode" class="form-label small">@Localizer["ZIP Code"]*</label>
            <input asp-for="@Model.PostCode"
                   type="text"
                   class="form-control" />
            <span asp-validation-for="@Model.PostCode" class="text-danger"></span>
        </div>
        <div class="col-5">
            <label asp-for="@Model.Town" class="form-label small">@Localizer["City"]*</label>
            <input asp-for="@Model.Town"
                   type="text"
                   class="form-control" />
            <span asp-validation-for="@Model.Town" class="text-danger"></span>
        </div>
    </div>
    <div class="row my-2>">
        <div class="col-8">
            <label asp-for="@Model.Address" class="form-label small">@Localizer["Address"]*</label>
            <input asp-for="@Model.Address"
                   type="text"
                   class="form-control" />
            <span asp-validation-for="@Model.Address" class="text-danger"></span>
        </div>
        <div class="col-4">
            <label asp-for="@Model.District" class="form-label small">@Localizer["District"]</label>
            <input asp-for="@Model.District"
                   type="text"
                   class="form-control" />
            <span asp-validation-for="@Model.District" class="text-danger"></span>
        </div>
    </div>
    <div class="my-2">
        <label asp-for="@Model.PhoneNumber" class="form-label small">@Localizer["Phone number* - we only use it if there is a problem with the delivery."]</label>
        <input asp-for="@Model.PhoneNumber"
               class="form-control" />
        <span asp-validation-for="@Model.PhoneNumber" class="text-danger"></span>
    </div>
    <div class="my-2">
        <label asp-for="@Model.Email" class="form-label small">@Localizer["Order confirmation email"]</label>
        <input asp-for="@Model.Email"
               class="form-control" />
        <span asp-validation-for="@Model.Email" class="text-danger"></span>
    </div>
    <div class="d-flex justify-content-end">
        <!-- Save Changes Start -->
        <button type="submit" class="btn btn-sm ms-3">@Localizer["Save"]</button>
        <!-- Save Changes End -->
    </div>
</form>
<!-- New Delivery Address End -->

LilsCareApp/Views/Shared/_DeliveryToOfficePartial.cshtml
@inject IViewLocalizer Localizer
@model AddressOrderDTO

<!-- New Delivery Office Start Start -->
<form asp-action="AddOfficeDelivery" method="post">
    <div class="d-flex justify-content-between align-items-center">
        <!-- Select Shipping Provider Start -->
        <div class="col-4">
            <h5>@Localizer["Courier"]</h5>
            <a class="nav-link dropdown-toggle fs-6" href="#" role="button" data-bs-toggle="dropdown">
                @{var providerName = @Model.ShippingProviders.FirstOrDefault(p => p.Id == Model.ShippingProviderId)?.Name; }
                @if (!string.IsNullOrEmpty(providerName))
                {
                    @providerName
                }
                else
                {
                    <span class="text-danger">@Localizer["Courier..."]</span>
                }
            </a>
            <ul class="dropdown-menu">
                <li>
                    @foreach (var provider in Model.ShippingProviders)
                    {
                        <a asp-action="SelectShippingProvider" asp-route-shippingProviderId="@provider.Id" class="dropdown-item">
                            @provider.Name
                        </a>
                    }
                </li>
            </ul>
        </div>
        <!-- Select Shipping Provider End -->
        <!-- Select Shipping City Start -->
        <div class="col-4">
            @if (!string.IsNullOrEmpty(providerName))
            {
                <h5>@Localizer["City"]</h5>
                <a class="nav-link dropdown-toggle fs-6" href="#" role="button" data-bs-toggle="dropdown">
                    @if (!string.IsNullOrEmpty(Model.ShippingProviderCity))
                    {
                        @Model.ShippingProviderCity
                    }
                    else
                    {
                        <span class="text-danger">@Localizer["City..."]</span>
                    }
                </a>
                <ul class="dropdown-menu">
                    <li>
                        @foreach (var city in Model.ShippingProviderCities)
                        {
                            <a asp-action="SelectShippingCity" asp-route-city="@city" class="dropdown-item">
                                @city
                            </a>
                        }
                    </li>
                </ul>
            }
        </div>
        <!-- Select Shipping City End -->
        <!-- Select Shipping Office Start -->
        <div class="col-4">
            @if (!string.IsNullOrEmpty(Model.ShippingProviderCity))
            {
                <h5>@Localizer["Courier office"]</h5>
                <a class="nav-link dropdown-toggle fs-6" href="#" role="button" data-bs-toggle="dropdown">
                    @{var officeAddress = Model.ShippingOffices.FirstOrDefault(so => so.Id == Model.ShippingOfficeId)?.OfficeAddress;}
                    @if (!string.IsNullOrEmpty(officeAddress))
                    {
                        @officeAddress
                    }
                    else
                    {

                        <span class="text-danger">@Localizer["Courier office..."]</span>
                    }
                </a>
                <ul class="dropdown-menu">
                    <li>
                        @foreach (var office in Model.ShippingOffices)
                        {
                            <a asp-action="SelectShippingOffice" asp-route-officeId="@office.Id" class="dropdown-item">
                                @office.OfficeAddress
                            </a>
                        }
                    </li>
                </ul>
            }
        </div>
        <!-- Select Office City End -->
    </div>
    <hr />
    <!-- Input Recipient Data Start-->
    @if (Model.ShippingOfficeId != null)
    {
        <div class="row my-2">
            <div class="col-6">
                <label asp-for="@Model.FirstName" class="form-label small">@Localizer["First Name"]*</label>
                <input asp-for="@Model.FirstName"
                       type="text"
                       class="form-control" />
                <span asp-validation-for="@Model.FirstName" class="text-danger"></span>
            </div>
            <div class="col-6">
                <label asp-for="@Model.LastName" class="form-label small">@Localizer["Last Name"]*</label>
                <input asp-for="@Model.LastName"
                       type="text"
                       class="form-control" />
                <span asp-validation-for="@Model.LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="my-2">
            <label asp-for="@Model.PhoneNumber" class="form-label small">@Localizer["Phone Number"]*</label>
            <input asp-for="@Model.PhoneNumber"
                   class="form-control" />
            <span asp-validation-for="@Model.PhoneNumber" class="text-danger"></span>
        </div>
        <div class="my-2">
            <label asp-for="@Model.Email" class="form-label small">@Localizer["Order confirmation email"]</label>
            <input asp-for="@Model.Email"
                   class="form-control" />
            <span asp-validation-for="@Model.Email" class="text-danger"></span>
        </div>
        <div class="d-flex justify-content-end">
            <!-- Save Changes Start -->
            <button type="submit" class="btn btn-sm ms-3">@Localizer["Save"]</button>
            <!-- Save Changes End -->
        </div>
    }
    <!-- Input Recipient Data Start-->
</form>
<!-- New Delivery Office Start End -->

LilsCareApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LIL'S CARE | @ViewData["Title"] </title>
    <link rel="icon"
          sizes="192x192"
          href="https://static.wixstatic.com/media/a6694c_487da19846414b3696763876d1233bd9%7Emv2.jpg"
          type="image/jpeg" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" asp-append-version="true" />

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" asp-append-version="true" />

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/site.css" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    @if (User.IsAdmin())
    {
        @RenderBody()
    }
    else
    {
        <header>
            <vc:header-component></vc:header-component>
        </header>
        <main role="main">
            <vc:shopping-bag-component></vc:shopping-bag-component>
            @RenderBody()
        </main>
        <footer class="border-top footer text-muted">
            <vc:footer-component></vc:footer-component>
        </footer>

        <!-- Back to Top -->
        <a href="#" class="btn rounded-circle back-to-top">
            <i class="fa fa-arrow-up"></i>
        </a>



        <!-- Redirecting to a specific element on a page after form submission -->
        <span id="scrollToElementId" style="display:none">@TempData["scrollToElementId"]</span>
        <script>
            // Check if there's a query parameter for scrolling
            const scrollToElementId = document.getElementById("scrollToElementId").textContent;
            var element = document.getElementById(scrollToElementId);
            if (element) {
                element.scrollIntoView({ behavior: 'instant' });
            }
        </script>
    }
</body>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontawesome/js/all.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</html>

LilsCareApp/Views/Shared/_SubscribersPartial.cshtml
@inject IViewLocalizer Localizer

@model SubscriberDTO
@{
}
<section id="add-to-subscribers" class="container w-50 text-center">
    <h3 class="h3">@Localizer["For the latest delights"]</h3>
 
        <div class="input-group">
        <input asp-for="EmailSubscriber" type="email"
                   class="form-control"
                   id="email"
               placeholder="@Localizer["Email..."]"
               name="EmailSubscriber" />
        <button type="submit" class="btn btn-lg">@Localizer["Sign me up!"]</button>
        </div>
    <span asp-validation-for="@Model.EmailSubscriber" class="text-danger" style="font-size: 12px"></span>
        <div class="form-check">
            <label class="form-check-label">
            <input asp-for="PrivacyPolicyCheckBox" type="checkbox" 
                   name="PrivacyPolicyCheckBox"
                   class="form-check-input"
                   data-val="true"
                   data-val-mustbetrue="@Localizer["Confirm agreement with the privacy policy."]" />
                <div class="d-flex justify-content-between">
                    <small>
                    @Localizer["I agree"]
                    <a asp-controller="TermsConditions"
                           target="_blank"
                       style="color: rgb(var(--app-btn-bg))">@Localizer["the conditions"]</a>
                    </small>
                <small style="margin-left: 120px">@Localizer["We send an email up to 1 time per month."]</small>
                </div>
            </label>
        </div>
    <span asp-validation-for="@Model.PrivacyPolicyCheckBox" class="text-danger" style="font-size: 12px"></span>
</section>