LilsCareApp/Areas/Admin/Controllers/ProductsController.cs
using LilsCareApp.Core.Contracts;
using LilsCareApp.Core.Models.AdminProducts;
using Microsoft.AspNetCore.Mvc;
using static LilsCareApp.Infrastructure.DataConstants.Product;

namespace LilsCareApp.Areas.Admin.Controllers
{
    public class ProductsController : AdminController
    {
        private readonly IAdminProductService _service;

        public ProductsController(IAdminProductService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(
            ProductSortType productSortType,
            string? search,
            int currentPage = 1,
            int productsPerPage = ProductsPerPages)
        {
            AdminProductsDTO products = await _service.GetProductsQueryAsync(productSortType, search, currentPage, productsPerPage);

            return View(products);
        }


        public async Task<IActionResult> ProductToShop(int id)
        {
            await _service.ProductToShopAsync(id);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            bool isOrdered = await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

LilsCareApp/Controllers/CheckoutController.cs
using LilsCareApp.Core.Contracts;
using LilsCareApp.Core.Models.Checkout;
using LilsCareApp.Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System.Security.Claims;
using System.Text;

namespace LilsCareApp.Controllers
{
    public class CheckoutController : BaseController
    {
        private readonly ILogger<CheckoutController> _logger;
        private readonly ICheckoutService _checkoutService;
        private readonly IProductsService _productsService;
        private readonly IAccountService _accountService;
        private readonly IGuestService _guestService;
        private readonly IEmailSender _emailSender;
        private readonly IStringLocalizer<CheckoutController> _localizer;
        private readonly IHttpContextManager _httpContextManager;

        public CheckoutController(
            ILogger<CheckoutController> logger,
            ICheckoutService checkoutService,
            IProductsService productsService,
            IAccountService accountService,
            IGuestService guestService,
            IEmailSender emailSender,
            IStringLocalizer<CheckoutController> localizer,
            IHttpContextManager httpContextManager)
        {
            _logger = logger;
            _checkoutService = checkoutService;
            _productsService = productsService;
            _accountService = accountService;
            _guestService = guestService;
            _emailSender = emailSender;
            _localizer = localizer;
            _httpContextManager = httpContextManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var userId = User.GetUserId();

            var order = await _checkoutService.GetOrderAsync(userId);

            if (userId != null)
            {
                order.ProductsInBag = await _productsService.GetProductsInBagAsync(userId);
            }
            else
            {
                order.ProductsInBag = await _guestService.GetProductsInBagAsync();
            }

            order = await _checkoutService.CalculateCheckout(order);

            _httpContextManager.SetSessionOrder(order);

            return View(order);
        }


        [AllowAnonymous]
        public async Task<IActionResult> SelectDeliveryMethod(int deliveryMethodId)
        {
            var order = _httpContextManager.GetSessionOrder();

            if (order is null || deliveryMethodId == 0)
            {
                return BadRequest();
            }

            order.Address = new AddressOrderDTO();
            order.DeliveryMethodId = deliveryMethodId;
            order.IsSelectedAddress = false;

            if (deliveryMethodId == 1)
            {
                order.Address.ShippingProviders = await _accountService.GetShippingProvidersAsync();
                order.Address.DeliveryMethodId = 1;
            }

            _httpContextManager.SetSessionOrder(order);

            return View(nameof(Index), order);
        }

        // Select the shipping provider for office delivery
        // Get the cities for the selected shipping provider.
        [AllowAnonymous]
        public async Task<IActionResult> SelectShippingProvider(int shippingProviderId)
        {
            var order = _httpContextManager.GetSessionOrder();

            if (shippingProviderId == 0 || order is null)
            {
                return BadRequest();
            }

            order.Address.ShippingProviderId = shippingProviderId;
            order.Address.ShippingProviderCities = await _accountService.GetShippingProviderCitiesAsync(shippingProviderId);
            order.Address.ShippingProviderCity = string.Empty;
            order.Address.ShippingOfficeId = null;

            _httpContextManager.SetSessionOrder(order);

            return View(nameof(Index), order);
        }


        // Select the city for office delivery
        // Get the shipping offices for the selected city.
        [AllowAnonymous]
        public async Task<IActionResult> SelectShippingCity(string city)
        {
            var order = _httpContextManager.GetSessionOrder();

            if (string.IsNullOrEmpty(city) || order is null)
            {
                return BadRequest();
            }

            order.Address.ShippingProviderCity = city;
            order.Address.ShippingOffices = await _accountService.GetShippingOfficesAsync(order.Address.ShippingProviderId, city);
            order.Address.ShippingOfficeId = null;

            _httpContextManager.SetSessionOrder(order);

            return View(nameof(Index), order);
        }

        // Select the shipping office for office delivery
        [AllowAnonymous]
        public IActionResult SelectShippingOffice(int officeId)
        {
            var order = _httpContextManager.GetSessionOrder();

            if (officeId == 0 || order is null)
            {
                return BadRequest();
            }

            order.Address.ShippingOfficeId = officeId;
            order.Address.ShippingOffice = order.Address.ShippingOffices.FirstOrDefault(x => x.Id == officeId);

            _httpContextManager.SetSessionOrder(order);

            return View(nameof(Index), order);
        }

        // Add address of type delivery to office
        [AllowAnonymous]
        public async Task<IActionResult> AddOfficeDelivery(AddressOrderDTO addressDTO)
        {
            var order = _httpContextManager.GetSessionOrder();

            if (addressDTO is null || order is null)
            {
                return BadRequest();
            }

            order.Address.FirstName = addressDTO.FirstName;
            order.Address.LastName = addressDTO.LastName;
            order.Address.PhoneNumber = addressDTO.PhoneNumber;
            order.Address.Email = addressDTO.Email;

            ModelState.Remove("Country");
            ModelState.Remove("PostCode");
            ModelState.Remove("Town");
            ModelState.Remove("Address");


            if (ModelState.IsValid && order.Address.ShippingOffice != null)
            {
                order.IsSelectedAddress = true;
                order = await _checkoutService.CalculateCheckout(order);
            }

            _httpContextManager.SetSessionOrder(order);

            return View(nameof(Index), order);
        }


        // Add address of type delivery to address
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> AddAddressDelivery(AddressOrderDTO addressDTO)
        {
            var order = _httpContextManager.GetSessionOrder();

            if (order is null || addressDTO is null)
            {
                return BadRequest();
            }

            order.Address = addressDTO;

            if (addressDTO is null)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                order.IsSelectedAddress = true;
                order = await _checkoutService.CalculateCheckout(order);
            }

            _httpContextManager.SetSessionOrder(order);

            return View(nameof(Index), order);
        }

        public async Task<IActionResult> EditDeliveryAddress()
        {
            var order = _httpContextManager.GetSessionOrder();

            if (order is null)
            {
                return BadRequest();
            }

            order.IsSelectedAddress = false;

            if (order.Address.DeliveryMethodId == 1 && order.Address.ShippingOffice != null)
            {
                order.Address.ShippingProviders = await _accountService.GetShippingProvidersAsync();
                order.Address.ShippingProviderId = order.Address.ShippingOffice.ShippingProviderId;
                order.Address.ShippingProviderCities = await _accountService.GetShippingProviderCitiesAsync(order.Address.ShippingProviderId);
                order.Address.ShippingProviderCity = order.Address.ShippingOffice.City;
                order.Address.ShippingOffices = await _accountService.GetShippingOfficesAsync(order.Address.ShippingProviderId, order.Address.ShippingProviderCity);
                order.Address.ShippingOfficeId = order.Address.ShippingOffice.Id;
            }

            _httpContextManager.SetSessionOrder(order);

            return View(nameof(Index), order);

        }


        // Select the payment method for the order.
        public async Task<IActionResult> DiscountWithPromoCode(int promoCodeId)
        {
            var order = _httpContextManager.GetSessionOrder();
            var userId = User.GetUserId();
            var ownerPromoCodeId = await _accountService.GetPromoCodeOwnerId(promoCodeId);

            if (userId != ownerPromoCodeId || order is null)
            {
                return BadRequest();
            }

            order.PromoCodeId = promoCodeId;

            order = await _checkoutService.CalculateCheckout(order);

            _httpContextManager.SetSessionOrder(order);

            return View(nameof(Index), order);
        }

        // Add/Remove product to cart.
        [AllowAnonymous]
        public async Task<IActionResult> AddToCart(int productId, int quantity)
        {
            var order = _httpContextManager.GetSessionOrder();

            if (order is null)
            {
                return BadRequest();
            }

            if (User.GetUserId() != null)
            {
                await _productsService.AddToCartAsync(productId, User.GetUserId(), quantity);
                order.ProductsInBag = await _productsService.GetProductsInBagAsync(User.GetUserId());
            }
            else
            {
                _guestService.AddToCart(productId, quantity);
                order.ProductsInBag = await _guestService.GetProductsInBagAsync();
            }

LilsCareApp/Views/Shared/Components/ShoppingBagComponent/Default.cshtml
@model IEnumerable<ProductsInBagDTO>
@inject IViewLocalizer Localizer
@{
}
<!-- Offcanvas Shopping Bag Start -->
<div class="offcanvas offcanvas-end @TempData["ShowBag"]" id="shopping-bag">
    <div class="offcanvas-header">
        <h2 class="offcanvas-title">@Localizer["My shopping bag"]</h2>
        <button type="button"
                class="btn-close"
                style="color:rgb(var(--app-btn-bg)"
                data-bs-dismiss="offcanvas"></button>
    </div>
    <div class="offcanvas-body">
            <hr />
        @if (Model.Count() == 0)
        {
            <p class="text-center fs-4">@Localizer["The shopping bag is empty"]</p>
        }
        else
        {
            <!-- Product in Shopping Bag Start -->
            @foreach (var product in Model)
            {
                <div class="d-flex justify-content-between id=" @product.Id"">
                    <div class="w-50">
                        <img src="@product.ImageUrl"
                             height="180px"
                             style="width: 100%; object-fit: cover"
                             alt="" />
                    </div>
                    <div class="w-50 fs-6 p-3">
                        <p>@product.Name</p>
                        <p>@Localizer["Price"]: @product.Price @Localizer["Currency"]</p>
                        <div class="d-flex justify-content-start align-items-center my-2">
                            <form asp-controller="Products" asp-action="AddToCart" asp-route-productId="@product.Id"
                                  method="post">
                                <input type="hidden" name="quantity" value="-1" />
                                <button type="submit"
                                        class="btn btn-inverce my-2" style="border: none">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </form>
                            <span class="mx-2"> @product.Quantity</span>
                            <form asp-controller="Products" asp-action="AddToCart" asp-route-productId="@product.Id"
                                  method="post">
                                <input type="hidden" name="quantity" value="1" />
                                <button type="submit"
                                        class="btn btn-inverce my-2" style="border: none">
                                    <i class="fa fa-plus"></i>
                                </button>
                            </form>
                        </div>
                        <a asp-controller="Products" asp-action="DeleteProductFromCart" asp-route-id="@product.Id" class="nav-link">
                            <i class="fas fa-trash-alt me-2"></i>@Localizer["Remove from shopping bag"]
                        </a>
                    </div>
                </div>
                <hr />
            }
            <!-- Product in Shopping Bag End -->
            <div class="fs-4 py-3">
                <span>@Localizer["Subtotal"] :</span><span class="float-end">@ViewBag.Total @Localizer["Currency"]</span>
            </div>
            <a asp-controller="Checkout" asp-action="Index" class="btn w-100">@Localizer["Purchase"]</a>
        }
    </div>
</div>
<!-- Offcanvas Shopping Bag End -->